version: '3'

services:
  mongodb:
    image: mongo:latest
    restart: always
    container_name: awan_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 130302
    volumes:
      - mongodb_data:/var/lib/mongodb
    ports:
      - "27017:27017"
    networks:
      - mongodb
volumes:
  mongodb_data:
networks:
  mongodb:
    driver: bridge